name: Daily Parser
on:
  schedule:
    - cron: "0 3 * * *"   # 8:00 PM PDT (03:00 UTC)
  workflow_dispatch:        # allow manual run
jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -r requirements.txt
      - name: Run parser
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python parse_email.py
